# -*- coding: utf-8 -*-
"""hw10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EUjB5hM3-zRF3cGc0oemZh2pPXuX-11H
"""

import os
import pickle

def input_scores():
    s = []
    i = 1
    while True:
        try:
            n = int(input(f'#{i}? '))
        except ValueError:
            print("Please enter a valid integer.")
            continue
        if n < 0:
            break
        s.append(n)
        i += 1
    return s

def get_average(s):
    total = sum(s)
    return total / len(s)

def show_scores(s):
    for n in s:
        print(n, end=' ')
    print()

def save_scores(s, filename='score.bin'):
    with open(filename, 'wb') as f:
        pickle.dump(s, f)

def load_scores(filename='score.bin'):
    if os.path.exists(filename):
        with open(filename, 'rb') as f:
            return pickle.load(f)
    return None

# Main program logic
scores = load_scores()
if scores is None:
    print('[점수 입력]')
    scores = input_scores()
    save_scores(scores)
else:
    print('[파일 읽기]')

print('\n[점수 출력]\n개인 점수: ', end='')
show_scores(scores)
avg = get_average(scores)
print(f'평균 : {avg:.1f}')