# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqQx4qPHynchm9HL5F9SsZc2PGNhUG3V
"""

def show_division(devidend, devisor):
  # quotient 나눗셈 연산의 몫
  quotient = devidend//devisor

  # remainder 나눗셈 연산의 나머지
  remainder = devidend %devisor

  #출력
  print("몫 =", quotient)
  print("나머지 =", remainder)


n1 = int(input("피젯수를 정수로 입력하세요 : "))
n2 = int(input("젯수를 정수로 입력하세요 :"))
show_division(n1,n2)



def show_division(dividend, devisor):
  # quotient 나눗셈 연산의 몫
  quotient = devidend//devisor

  # remainder 나눗셈 연산의 나머지
  remainder = devidend %devisor

  #출력
  print("몫 =", quotient)
  print("나머지 =", remainder)


n1 = int(input("피젯수를 정수로 입력하세요 : "))
n2 = int(input("젯수를 정수로 입력하세요 :"))
show_division(divisor = n2, dividend = n1)

def show_division(dividend, divisor):
  # quotient 나눗셈 연산의 몫
  quotient = dividend // divisor

  # remainder 나눗셈 연산의 나머지
  remainder = dividend % divisor

  # 출력
  print("몫 =", quotient)
  print("나머지 =", remainder)


n1 = int(input("피젯수를 정수로 입력하세요: "))
n2 = int(input("젯수를 정수로 입력하세요: "))
show_division(dividend=n1, divisor=n2)

n1 = 1
n2 = n1
res = n1 + n2
n1 = n1 +1
print(n1)

n1 = 0b10101101
n2 = 0b00001111

print(bin(n1 & n2))
print(bin(n1 | n2))
print(bin(n1 ^ n2))
print(bin(~n2))

n2 = 0b00001111
print(bin(n2 >> 2))
print(bin(n2 << 2))

"""##거스름돈"""

def show_change(amount):
  print("잔돈 : ",amount,"원")
  n1 = amount // 5000
  amount %= 5000

  n2 = amount //1000

  print("> 5000원권", n1,"장")
  print("> 1000원권", n2,"장")



total_cost = int(input('구매한 물건의 총구매 금액은?'))
payment = int(input('고객으로부터 지불받은 금액은?'))
change = payment - total_cost
show_change(change)

def show_change(amount):
  print('잔돈',amount,'원')
  n1 = amount // 5000
  amount %= 5000

  n2 = amount //1000

  print('5000원권', n1,'장')
  print('1000원권', n2,'장')


total_cost = int(input(''))
payment = int(input(''))

change = payment - total_cost

show_change(change)

def fahrenheit_to_celsius(F):
  cels = 5/9*(F-32)
  return cels

def get_real(prompt):
  res = float(input(prompt))
  return res


ftemp = get_real("변환하고자 하는 화씨온도?")
ctemp = fahrenheit_to_celsius(ftemp)
print("화씨",ftemp,"도는 섭씨",ctemp ,"도")

def convert_time(T):
  h1 = T // 3600
  T %= 3600
  h2 = T // 60
  T %= 60
  h3 = T
  print(time_1,"초는",h1,"시간",h2,"분",T,"초이다.")

def get_integer(prompt):
  res = int(input(prompt))
  return res


time_1 = get_integer("변환하고자 하는 시간(초)?  ")
c_time = convert_time(time_1)

def set_all_bits(n):
  return (1 << n) -1
def get_integer(prompt):
  return int(input(prompt))

n = get_integer("설정할 비트 수는? ")
b= set_all_bits(n)

print(n, ' 비트를 모두 1로 설정한 수는', b, '(', bin(b),')이다.')