# -*- coding: utf-8 -*-
"""hw2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1voIsNymiu0yIhOtY99nyrTvRAJi064dy
"""

def exchange(amount):
    print('입력된 금액:', amount, '원')

    # 500원 개수
    n_500 = amount // 500
    amount %= 500
    # 100원 개수
    n_100 = amount // 100
    amount %= 100
    # 50원 개수
    n_50 = amount // 50
    amount %= 50
    # 10원 개수
    n_10 = amount // 10

    print('500원 동전 개수:', n_500, '개')
    print('100원 동전 개수:', n_100, '개')
    print('50원 동전 개수:', n_50, '개')
    print('10원 동전 개수:', n_10, '개')

def get_integer(prompt):
  res = int(input(prompt))
  return res

amount = get_integer("동전으로 교환하고자 하는 금액은?")
# 동전으로 교환
exchange(amount)