# -*- coding: utf-8 -*-
"""hw5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QPQBmmoRJQMrmTE2tgAjT6Hlpm1sEVG
"""

def read_single_digit(n):
  digits = {1: '일', 2: '이', 3: '삼', 4: '사',
            5: '오', 6: '육', 7: '칠', 8: '팔', 9: '구'}
  return digits[n]


def read_number(n):
  if len(n) == 1:
    return read_single_digit(int(n))
  elif len(n) == 2 :
    two_digit = read_single_digit(int(n[0]))
    single_digit = read_single_digit(int(n[1]))
    return two_digit + single_digit
  elif len(n) == 3:
    three_digit = read_single_digit(int(n[0]))
    two_digit = read_single_digit(int(n[1]))
    single_digit = read_single_digit(int(n[2]))
    return three_digit + two_digit + single_digit
  else :
    print('잘못된 숫자 입력')

nums = input("세 자리 정수 입력 :")

kor_digits = read_number(nums)
print(kor_digits)
