# -*- coding: utf-8 -*-
"""hw6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqMVyxxVoppKq8VSJCP0Pfoy5WJ1GZPD
"""

for y in range(1, 10):
    for x in range(2, 6):
        print(x, "X", y, "=", x*y, end="\t")
        if y==9 :
          print(end="")
    print()

print()


for y in range(1, 10):
    for x in range(6, 10):
        print(x, "X", y, "=", x*y, end="\t")
        if y==9 :
          print(end="")
    print()