# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7JZD2L_cioqjtMd2cxBdoLg7Qktail_
"""

list1 = [11,22,33,44]
list2 = ['단촐','단아','당당']
list3 = []
print(list1)
print(list2)
print(list3)

list4 = [11, '홍길동',19,180.5]
list5 = [11,'홍길동',[10,10,92,100]]
print(list4)
print(list5)

list4 = [11,'홍길동', 19, 180.5]
print(list4[1], '님의 키는', list4[-1],'cm 입니다')

list = [11, 22, 33, 44, 55]
sub_list = list[1:3]
print(sub_list)
print(sub_list[0])

nums = [11,22,33,44,55]
nums[0] = -1
print(nums)

nums[1:3] = [100,200,300]
print(nums)



nums1=[11,22,33]
nums2=[]
nums2=nums1[:]
nums2[0] = 0
print(nums1)
print(nums2)

nums1 =[11,22,33]
nums2 = nums1[:]

print(nums1 == nums2)

nums2[1] = 0
print(nums1 == nums2)
print(nums1 > nums2)
print(nums1 < nums2 )

nums1 = [11,22,33]
nums2 = [44, 55]

nums3 = nums1 + nums2
print(nums3)

nums4 = nums1 *2
print(nums4)

t1 = (11,22,33,44,55)
print(t1[0])
print(t1[1:3])

t2 = (66,77)
t3 = t1+t2
print(t3)

t4=t2*3

print(t4)

d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}
print(d['python'])

print(d[0])

d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}
print(d.get('python'))

res = d.get(0)
print(res)

d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}

key = 0
if key in d :
  print(d[key])
else :
  print(f'오류 : 유효하지 않은 키 {key}')

d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}
d['Python'] = '파이썬'
print(d)

d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}
d['python'] = 'PYTHON'
print(d)



d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}
del d['basic']
print(d)

d={'python':'파이썬', 'basic':'기초', 'programming':'프로그래밍'}
d.clear()
print(d)

scores = []
print('[점수 입력]')
for i in range(3):
  n = int(input(f'#{i+1}? '))
  scores.append(n)
print('\[점수 출력]')
print(f'입력 점수 : {scores[0]} {scores[1]} {scores[2]}')
avg = (scores[0] + scores[1] + scores[2]) / len(scores)
print(f'평균 : {avg:.1f}')

scores = []
print('[점수 입력]')
for i in range(3):
  n = int(input(f'#{i+1}? '))
  scores.append(n)
print('\[점수 출력]')
print(f'입력 점수 : {scores[0]} {scores[1]} {scores[2]}')
avg = (scores[0] + scores[1] + scores[2]) / len(scores)
print(f'평균 : {avg:.1f}')


print( '\n[검색]')
s = int(input('찾고자 하는 점수는? '))
if s in scores:
  idx = scores.index(s)
  print(f'{s} 점은 {idx+1}번 학생의 점수입니다')
else :
  print(f'{s}점을 받은 학생은 없습니다.')

shopping_bag = []
while True:
  item = input("상품명?")
  if item =='':
    break
  shopping_bag.append(item)
  print(f'장바구니에 {item}가(이) 담겼습니다.\n')


print(f'\n>>>> 장바구니 보기 : {shopping_bag}')

