# -*- coding: utf-8 -*-
"""hw8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NZ5PcYCMDIjssev8pCIvKwFhji9gA9e
"""

def buy(shopping_bag):
    item = input("상품명? ")
    if item == '':
        return False
    quantity = int(input("수량은? "))
    shopping_bag[item] = quantity
    print(f'장바구니에 {item} {quantity}개가 담겼습니다.\n')
    return True

def show(shopping_bag):
    print(f'\n>>>> 장바구니 보기 : {shopping_bag}\n')

def find(shopping_bag):
    print('[검색]')
    search_item = input("장바구니에서 확인하고자 하는 상품은? ")
    if search_item in shopping_bag:
        print(f'{search_item}은(는) {shopping_bag[search_item]}개 담겨 있습니다.')
    else:
        print("해당 상품이 장바구니에 없습니다.")

shopping_bag = {}
while True:
    if buy(shopping_bag) == False:
        break

show(shopping_bag)
find(shopping_bag)

def buy(shopping_bag):
    item = input("상품명? ")
    if item == '':
        return False
    quantity = int(input("수량은? "))
    shopping_bag[item] = quantity
    print(f'장바구니에 {item} {quantity}개가 담겼습니다.\n')
    return True

def show(shopping_bag):
    print(f'\n>>>> 장바구니 보기 : {shopping_bag}\n')

def find(shopping_bag):
    while True:
        print('[검색]')
        search_item = input("장바구니에서 확인하고자 하는 상품은? ")
        if search_item == '':
          print("프로그램을 종료합니다.")
          break
        elif search_item in shopping_bag:
            print(f'{search_item}은(는) {shopping_bag[search_item]}개 담겨 있습니다.')
        else:
            print("해당 상품이 장바구니에 없습니다. 다시 입력해 주세요.")

shopping_bag = {}
while True:
    if buy(shopping_bag) == False:
        break

show(shopping_bag)
find(shopping_bag)